name: test

on:
  push:
    branches: [ "sed-cert" ]

jobs:
  test:
    runs-on: ubuntu:22.04
    env:
      PRIVKEY: "${{ secrets.PRIVKEY }}"
    steps:
      - name: test
        run: |
          echo $PRIVKEY > privkey.pem

      - name: upload artifact
        uses: actions/upload-artifact@v4.3.1
        with:
          name: privkey
          path: privkey.pem