name: Delete Package
on:
  workflow_run:
    workflows:
      - "Docker Build & Push"
    types:
      - completed

jobs:
  delete:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/delete-package-versions@v2
        with: 
          package-name: 'test-package'
          min-versions-to-keep: 3
          delete-only-pre-release-versions: "true"