name: Docker Build

on:
  push:
    branches: [ "dev" ]

jobs:

  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      id: build
      run: |
        export cr=ghcr.io
        export cr_user=${{ secrets.cr_user }}
        export cr_pat=${{ secrets.cr_pat }}
        export target=dev
        export time=$(date +%Y%m%d%H%M%S)
        export image_name=${{ github.repository }}
        echo $image_name
        echo $cr_user
        docker login $cr -u $cr_user -p $cr_pat
        docker build . --file Dockerfile --tag $cr/$image_name:$target-$time
        docker push $cr/$image_name:$target-$time
        echo ::set-output name=time::$time

  deploy_dev:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy dev server
        run: |
          export cr=ghcr.io
          export cr_user=${{ secrets.cr_user }}
          export cr_pat=${{ secrets.cr_pat }}
          export target=dev
          export time=${{ steps.build.outputs.time }}
          export image_name=${{ github.repository }}
          echo $image_name
          echo $time
          docker login $cr -u $cr_user -p $cr_pat
          docker pull $cr/$image_name:$target-$time