name: Docker Build

on:
  push:
    branches: [ "dev" ]

jobs:

  build:

    runs-on: ubuntu-latest
    outputs:
      time: ${{ steps.build.outputs.time }}
      image_name: ${{ steps.build.outputs.image_name }}
      target: ${{ steps.build.outputs.target }}
      cr: ${{ steps.build.outputs.cr }}
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      id: build
      run: |
        export cr=ghcr.io
        export target=dev
        export time=$(date +%Y%m%d%H%M%S)
        export image_name=${{ github.repository }}
        docker build . --file Dockerfile --tag $cr/$image_name:$target-$time
        mkdir -p /tmp
        docker save -o /tmp/artifact.tar $cr/$image_name:$target-$time
        echo ::set-output name=time::$time
        echo ::set-output name=image_name::$image_name
        echo ::set-output name=target::$target
        echo ::set-output name=cr::$cr
    - uses: actions/upload-artifact@master
      with:
        name: artifact
        path: /tmp/artifact.tar

  push:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/download-artifact@master
      with:
        name: artifact
        path: /tmp/artifact.tar
    - name: Push to Github Container registry
      id: push
      run: |
        export image_name=${{ needs.build.outputs.image_name }}
        export target=${{ needs.build.outputs.target }}
        export time=${{ needs.build.outputs.time }}
        export cr=${{ needs.build.outputs.cr }}
        export cr_user=${{ secrets.cr_user }}
        export cr_pat=${{ secrets.cr_pat }}
        docker login $cr -u $cr_user -p $cr_pat
        docker load -i /tmp/artifact.tar
        docker push $cr/$image_name:$target-$time
          


  pull:
    runs-on: ubuntu-latest
    needs: push
    steps:
      - name: Deploy dev server
        run: |
          export cr=ghcr.io
          export cr_user=${{ secrets.cr_user }}
          export cr_pat=${{ secrets.cr_pat }}
          export target=dev
          export time=${{ needs.build.outputs.time }}
          export image_name=${{ github.repository }}
          echo $image_name
          echo $time
          docker login $cr -u $cr_user -p $cr_pat
          docker pull $cr/$image_name:$target-$time