name: Docker Build

on:
  push:
    branches: [ "dev" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
        export time=$(date +%Y%m%d%H%M%S)
        export image-name=${{ github.repository }}:$time
        echo $image-name
        # docker build . --file Dockerfile --tag my-image-name:$(date +%s)
